Change Websocket client to Jetty 11.0.13
obs-websocket-community-projects/obs-websocket-java pull request #163
Opened 2023-01-03 16:44 UTC by DorianSnowball

Update to Jetty Websocket requires minimal changes and does not break any tests.

Closes #162

2023-01-03 16:47 UTC, ChristopheCVB requested changes
It seems to be breaking all tests though :/

2023-01-03 16:55 UTC, DorianSnowball commented
Running them local worked without an issue due to me compiling it with Java 17. The CI/CD Pipeline seems to only accept Java 8 code though.
Looking at it, it appears that Jetty 11 uses Java 11+, that's why the CI/CD pipeline fails.
Curious though why running it locally succeeded even though 
`java.sourceCompatibility = JavaVersion.VERSION_1_8` is set in client/build.gradle

2023-01-03 16:57 UTC, ChristopheCVB commented
That update will have to wait then, this library is meant to suport Java 8. Maybe for the v3?

2023-01-03 17:03 UTC, DorianSnowball commented
I would recommend explicitly stating that this library is meant to support Java 8 in the README.md of the project then, to avoid future problems like this.

Idk what's the correct handling of this PR is now, if it's not going into v2.

2023-01-09 10:13 UTC, ChristopheCVB commented
Let's get back to this when we work on v3

2023-01-09 10:13 UTC, closed without merging

2026-03-20 12:45 UTC, Jilocasin commented
Any updates on this topic? Sorry for commenting on an old issue, but seems like nothing has happened for 3 years when it comes to compatibility.